### ISSUE TITLE
I get a error named: "Network Error" when tried to register an user.

### ISSUE THREAD

**Issue by OmerFarukOruc** [Arun2629/IoT-Dashboard#1]
As title says, i get an error. What can be the problem and thanks.
![image](https://user-images.githubusercontent.com/7347742/211315505-2334ef5e-4920-4de7-b4c1-962a3de16453.png)

**Comment by Arun2629** [comment]
Hi sir,
Have you strted up the database?
It might be due to backend being not running. Because its working in my
local system

**Comment by Arun2629** [comment]
I will just clone my repo and check for errors sir.

**Comment by Arun2629** [comment]
Hi sir
Just cross checked it again. It might be due to the backend being not
running sir that its showing network error.

**Comment by OmerFarukOruc** [comment]
My backend is running but i guess it's related MongoDB related. Dunno how to check if it s or not.

**Comment by Arun2629** [comment]
If you want sir we can have a google meet and i can share my screen and
show you the working.
Meanwhile i will try to figure out why is this happening

**Comment by OmerFarukOruc** [comment]
All good, i made it running now. Thanks for the help. :))
